### ISSUE TITLE
Issue w/ Bool - Invalid memory access (signal 11) at address 0x0

### ISSUE THREAD

**Issue by lwakefield** [will/crystal-pg#288]
I've been chasing this error for a hot second, and have finally narrowed (reproducible, at least for me) it down to "pg"!

The wrinkle is, the crash only shows up when built with the `--release` flag, which of course has more obtuse debugging output...

From what I can tell so far, this only occurs when querying and casting for `Bool`. Though TBD if I can recreate with other data types...

So with:

```crystal
require "pg"

conn = PG.connect("postgres://postgres@localhost:5432/postgres")
pp conn.query_one("select true", as: Bool)
conn.close
```

and 

```
$ crystal run tmp/pg_crash.cr
true
```

but...
```
$ crystal run --release tmp/pg_crash.cr
Invalid memory access (signal 11) at address 0x0
[0x60031319c649] ?? +105566321624649 in /home/codespace/.cache/crystal/crystal-run-pg_crash.tmp
[0x60031319c600] ?? +105566321624576 in /home/codespace/.cache/crystal/crystal-run-pg_crash.tmp
[0x7afceeeea420] ?? +135226758964256 in /lib/x86_64-linux-gnu/libpthread.so.0
[0x6003131fd359] ?? +105566322021209 in /home/codespace/.cache/crystal/crystal-run-pg_crash.tmp
[0x600313168802] __crystal_main +60226 in /home/codespace/.cache/crystal/crystal-run-pg_crash.tmp
[0x60031316fc8b] main +59 in /home/codespace/.cache/crystal/crystal-run-pg_crash.tmp
[0x7afceec8f083] __libc_start_main +243 in /lib/x86_64-linux-gnu/libc.so.6
[0x600313159bfe] _start +46 in /home/codespace/.cache/crystal/crystal-run-pg_crash.tmp
[0x0] ???
```

Creating this issue in case it is obvious to others, others experience something similar, or others have pointers for me. But ideally I'm planning on chasing this down myself...

**Comment by lwakefield** [comment]
Well... I found a "fix" but I'm not trying to work out _why_ it works, because it feels very hacky...

https://github.com/lwakefield/crystal-pg/commit/1012f8b4a91b1f0c7b941a3fca704ccf9b428bbe

```crystal
      begin
-       yield @sized_io
+       r = yield @sized_io
+       r
```

**Comment by straight-shoota** [comment]
This smells like a bug in LLVM (or the Crystal compiler).

I can reproduce the invalid memory access only on Crystal built with LLVM 18, not with LLVM 17.

**Comment by lwakefield** [comment]
yes - I was coming to a conclusion that I was going to be out of my depth shortly... So that checks out!

@straight-shoota - do you have any tips to generate useful diagnostics? I'm planning on simply logging an issue over on https://github.com/crystal-lang/crystal with as much diagnostic information as possible (everything I posted here plus some versions of crystal/llvm/pg).

**Comment by straight-shoota** [comment]
I created https://github.com/crystal-lang/crystal/issues/14898 to track this issue in the Crystal repo.

**Comment by will** [comment]
Thanks @straight-shoota for opening it there, and nice find @lwakefield! I'm going to close this one here since it seems like the new issue in crystal-lang/crystal is a better spot. But if anyone disagrees let me know and we can reopen this one.

**Comment by compumike** [comment]
Just wanted to say thanks to everyone in this discussion! :heart:  Great job tracking it down to such a simple example @lwakefield -- this appears to have fixed our issue too: [Invalid memory access (signal 11) on 1.13.1, not present on 1.12.2?](https://forum.crystal-lang.org/t/invalid-memory-access-signal-11-on-1-13-1-not-present-on-1-12-2/7051)

**Comment by zw963** [comment]
Don't know if this issue is related to https://github.com/crystal-lang/crystal-sqlite3/issues/96, but anyway, will try later.

**Comment by straight-shoota** [comment]
If it reproduces with a Crystal compiler <= 1.13.1 that uses LLVM 18, but not when using LLVM < 18, it's probably the same issue.
You may also check against Crystal nightly where the bug is fixed and it should work regardless of LLVM version.

**Comment by zw963** [comment]
I can still reproduce my issue on Crystal 1.13.2, as following screenshot.

![image](https://github.com/user-attachments/assets/539a758d-7b31-43e1-91e2-f9513827c917)
